// 언어 전환·검색창/PDF/로고 바인딩
function syncTips(){ const ko=LANG!=='en'; $('#exCase').hidden=!(ko&&MODE==='case'); $('#exPat').hidden=!(ko&&MODE==='patent'); $('#tipCase').hidden=!(ko&&MODE==='case'); $('#tipPat').hidden=!(ko&&MODE==='patent'); $('#tipUs').hidden=!(LANG==='en'&&MODE==='us'); $('#exUs').hidden=!(LANG==='en'&&MODE==='us'); }
function applyLang(){ const t=T[LANG]; const ms=document.querySelectorAll('#modes .m'); ms[0].textContent=t.modes[0]; ms[1].textContent=t.modes[1]; ms[0].dataset.m=LANG==='en'?'us':'case'; ms[1].hidden=LANG==='en'||IS_MOBILE; { const pw=$('#pkwarn'); if(pw){ pw.hidden=!(IS_MOBILE&&LANG==='en'); pw.textContent='⚠️ Caution: Only load the packs you actually need! I did warn you, didn\'t I? The app will crash.'; } }   /* 미국판 아이패드 전용 경고(사용자 문구 영역) — 한국 판례는 작아서 불필요 */   /* 아이패드: 특허 공보 미지원(메모리) → 탭 숨김(삭제 금지: applyLang 이 ms[1] 참조) */ $('#modes').style.display=LANG==='en'?'none':'';
  $('#opts_k').textContent=t.k; $('#hybl').textContent=t.hyb; $('#footnote').textContent=t.foot; syncTips();
  $('#logo').title=L('처음으로','Home'); $('#plus').title=L('PDF 넣기 — 소장·공소장·준비서면은 청구원인·공소사실만, 특허 명세서는 요약·청구범위만 골라 검색창에 옮깁니다 (파일은 저장되지 않음)','Add a PDF — complaints, indictments and briefs: only the statement of facts / cause of action is extracted into the search box (the file is never stored)');
  $('#packs .rbar b').textContent=L('데이터 팩','Data packs'); $('#pkhint').textContent=L('체크한 팩만 내려받아 엔진에 싣습니다. 해제하면 메모리에서 내립니다. 검색 범위는 검색창 아래 칩으로 그때그때 고르면 됩니다.','Only checked packs are downloaded and loaded into the engine; unchecking unloads them. Narrow a search any time with the chips under the search box.'); $('#pkapply').textContent=L('선택한 팩 내려받기 · 적용','Download selected · Apply');
  $('#rprev').textContent=L('← 이전','← Prev'); $('#rnext').textContent=L('다음 →','Next →'); $('#rcopy').textContent=L('인용 복사','Copy citation'); $('#rcopy').title=L('본문을 드래그해 두면 그 문장과 출처를 함께 복사합니다','Select text in the opinion first to copy it together with its citation'); $('#pkopen').textContent=L('데이터 팩 선택','Data packs'); $('#pkcheck').textContent=L('업데이트 확인','Check for updates'); const pt=document.querySelectorAll('.pkt'); if(pt[0]) pt[0].textContent=L('팩 선택','Choose packs'); if(pt[1]) pt[1].textContent=L('설치된 팩','Installed'); $('#joke').textContent=L('“의뢰인 얘기를 그대로 넣어도 비밀유지특권 유지되냐고요?” 저희는 님들 의뢰인의 사생활과 범죄 내역에 관심이 없습니다 ㅇㅅㅇ 데이터 팩 받고 인터넷 꺼보세요. 돌아갑니다.','“Can I paste my client’s whole story in here and keep privilege?” We have zero interest in your client’s private life or rap sheet ㅇㅅㅇ Download the packs, turn off your Wi-Fi, and watch it still work.'); }
function setLang(l){ LANG=l; document.querySelectorAll('#lang .l').forEach(x=>x.classList.toggle('on',x.dataset.l===l)); MODE=LANG==='en'?'us':'case'; document.querySelectorAll('#modes .m').forEach((x,i)=>x.classList.toggle('on',i===0)); applyLang(); q.placeholder=PH[MODE]; drawScope(); if(IS_TAURI) inv('prewarm',{mode:MODE}).catch(()=>{}); try{ localStorage.setItem('nike.country', l); }catch(e){} drawAppUpd(); if(window.__S&&window.__ready&&!(window.__S.stage==='warm'&&window.__S.done<window.__S.total)) $('#ready').textContent=readyText(window.__S); }
(function(){ let c=null; try{ c=localStorage.getItem('nike.country'); }catch(e){} if(!c){ $('#country').hidden=false; document.querySelectorAll('#country .card').forEach(cd=>cd.onclick=()=>{ $('#country').hidden=true; setLang(cd.dataset.c); try{ localStorage.setItem('nike.country', cd.dataset.c); }catch(e){} if(window.__nopacks&&!window.__introShown){ window.__introShown=true; $('#pkintro').hidden=false; openPacks(); } else q.focus(); }); } else if(c==='en'){ setTimeout(()=>setLang('en'),0); } })();
