// 데이터 팩 패널·업데이트
let PKTAB='sel';
function bindDel(){ const mb=b=>b>=1e9?(b/1e9).toFixed(1)+' GB':(b/1e6).toFixed(0)+' MB'; document.querySelectorAll('#pklist .pkdel, #pklist .usdel, #pklist .pkdelall').forEach(a=>a.onclick=async e=>{ e.preventDefault(); e.stopPropagation(); const keys=(a.dataset.keys||a.dataset.k).split(','); const st=$('#pkstatus');
  st.textContent=L(`삭제 중… (${keys.length}개)`,`Deleting… (${keys.length})`); const ab=$('#pkapply'); ab.disabled=true; ab.style.opacity='.5'; try{ const freed=await inv('delete_packs',{keys}); st.textContent=L(`삭제됨 · ${mb(freed)} 확보 — 엔진을 다시 싣는 중`,`Deleted · ${mb(freed)} freed — reloading the engine`); window.__ready=false; window.__reloading=true; setTimeout(()=>window.__poll&&window.__poll(),300); }catch(err){ st.textContent=L('삭제 실패: ','Delete failed: ')+err; } }); }
function drawInstalled(ps){ const mb=b=>b>=1e9?(b/1e9).toFixed(1)+' GB':(b/1e6).toFixed(0)+' MB'; const inst=ps.filter(p=>p.installed); const kr=inst.filter(p=>!p.key.startsWith('us_')), us=inst.filter(p=>p.key.startsWith('us_'));
  const row=p=>`<div class="instrow"><b>${esc(PLABEL[p.key]||p.label)}</b><span class="sz">${p.recs.toLocaleString()}${L('건',' cases')} · ${mb(p.bytes)}</span><span class="${p.selected?'on':'off'}">${p.selected?L('검색 중','in use'):L('꺼짐','off')}</span><a href="#" class="pkdel" data-k="${p.key}" title="${L('디스크에서 삭제','Delete from disk')}">✕</a></div>`;
  const card=(title,items)=>items.length?`<div class="pkcard"><div class="hd"><b>${title}</b><span class="band">${items.length}${L('개',' packs')} · ${mb(items.reduce((a,p)=>a+p.bytes,0))}</span><span class="ops"><a href="#" class="pkdelall" data-keys="${items.map(p=>p.key).join(',')}">${L('전부 삭제','Delete all')}</a></span></div>${items.map(row).join('')}</div>`:'';
  const tot=inst.reduce((a,p)=>a+p.bytes,0);
  return `<p class="band" style="margin:0 0 6px">${L(`이 컴퓨터에 내려받은 팩 ${inst.length}개 · ${mb(tot)}. ✕ 를 누르면 디스크에서 지웁니다(다시 받을 수 있음).`,`${inst.length} packs on this computer · ${mb(tot)}. ✕ removes a pack from disk (you can download it again).`)}</p>`+(LANG==='en'?card('United States',us)+card('대한민국',kr):card('판례 · 해석례 · 심판 · 특허',kr)+card('United States',us))+(inst.length?'':`<p class="band">${L('설치된 팩이 없습니다.','No packs installed.')}</p>`); }
async function openPacks(){ $('#packs').classList.add('on'); document.querySelectorAll('.pkt').forEach(t=>{ t.classList.toggle('on',t.dataset.t===PKTAB); t.onclick=()=>{ PKTAB=t.dataset.t; openPacks(); }; }); $('#pkapply').style.display=PKTAB==='sel'?'':'none'; if(LANG==='en') $('#pkintro').innerHTML='<b>Download only what you need.</b> Pick the courts you practice in, then the eras. Each state-era pack is tens to hundreds of MB; you can add or remove packs any time, and everything you download is searched only on this computer.'; $('#pklist').innerHTML='<p class="band">'+L('불러오는 중…','Loading…')+'</p>';
  try{ const ps=await inv('packs'); window.__PS=ps; const off=ps.some(p=>p.offline); $('#pkinfo').textContent=off?L('오프라인 · 설치된 팩만 표시','Offline · showing installed packs only'):''; if(PKTAB==='inst'){ $('#pklist').innerHTML=drawInstalled(ps); bindDel(); $('#pksum').textContent=''; return; } const mb=b=>b>=1e9?(b/1e9).toFixed(1)+' GB':(b/1e6).toFixed(0)+' MB'; const by=Object.fromEntries(ps.map(p=>[p.key,p]));
    const row=p=>`<label class="pkrow"><input type="checkbox" data-k="${p.key}" data-b="${p.bytes}" ${p.selected?'checked':''}><b>${esc(PLABEL[p.key]||p.label)}</b><span class="sz">${p.recs.toLocaleString()}${L('건',' cases')} · ${mb(p.bytes)}</span><span class="st ${p.update?'up':p.installed?'ok':''}">${p.update?L('업데이트','update'):p.installed?L('설치됨','installed'):L('내려받기','download')}</span></label>`;
    const group=(title,keys,note)=>{ const items=keys.map(([k])=>by[k]).filter(Boolean); if(!items.length) return ''; const tot=items.reduce((a,p)=>a+p.bytes,0);
      return `<div class="pkcard" data-group="${title}"><div class="hd"><b>${title}</b><span class="band">${items.length}개 · ${mb(tot)}${note?' · '+note:''}</span><span class="ops"><a href="#" class="gsel" data-on="1">전체 선택</a><a href="#" class="gsel" data-on="0">전체 해제</a></span></div>${items.map(row).join('')}</div>`; };
    const usAvail=k=>ERAS.some(([e])=>by[k+'_'+e]); const usSize=k=>ERAS.reduce((a,[e])=>a+((by[k+'_'+e]||{}).bytes||0),0);
    const usTotal=[...USP.map(([k])=>k),...STATES.map(([c])=>'us_'+c)].reduce((a,k)=>a+usSize(k),0);
    const hidden=[...Object.keys(by)].filter(k=>k.startsWith('us_')).map(k=>`<input type="checkbox" class="uspk" data-k="${k}" data-b="${by[k].bytes}" ${by[k].selected?'checked':''} hidden>`).join('');
    const us=`<div class="pkcard" data-group="us"><div class="hd"><b>United States</b><span class="band">${mb(usTotal)} available · pick courts, then eras</span><span class="ops"><a href="#" id="usClear">Clear all</a></span></div>
      <div class="usrow"><span class="lbl">Federal</span><label><input type="checkbox" id="usScotus" ${usAvail('us_scotus')?'':'disabled'}> U.S. Supreme Court${usAvail('us_scotus')?' · '+mb(usSize('us_scotus')):' · not available yet'}</label><label title="Court of Appeals for each checked state’s circuit + that state’s federal district & bankruptcy courts"><input type="checkbox" id="usFedLower" ${usAvail('us_fed_ca2')?'':'disabled'}> Circuit &amp; district courts of checked states${usAvail('us_fed_ca2')?'':' · not available yet'}</label><label title="Nationwide appeals in patents, trademarks, international trade and federal claims (Washington, D.C.)"><input type="checkbox" id="usFedCafc" ${usAvail('us_fed_cafc')?'':'disabled'}> Federal Circuit (patents)${usAvail('us_fed_cafc')?' · '+mb(usSize('us_fed_cafc')):' · not available yet'}</label><label title="Court of Federal Claims · Tax Court · Court of International Trade · Veterans · Military"><input type="checkbox" id="usFedOther" ${usAvail('us_fed_other')?'':'disabled'}> Other federal courts${usAvail('us_fed_other')?' · '+mb(usSize('us_fed_other')):' · not available yet'}</label></div>
      <div class="usrow"><span class="lbl">States</span><span class="band">Packs are large (a state runs 0.5–7 GB across its eras). Download only the courts you practice in — you can add more any time.</span></div>
      <div class="usgrid" id="usgrid">${STATES.map(([c,n])=>`<label class="${usAvail('us_'+c)?'':'na'}" title="${n}${usAvail('us_'+c)?' · '+mb(usSize('us_'+c)):' · not available yet'}"><input type="checkbox" data-st="${c}" ${usAvail('us_'+c)?'':'disabled'}><span class="cd">${c.toUpperCase()}</span><span>${n}</span></label>`).join('')}</div>
      <div class="usrow"><span class="lbl">Eras</span>${ERAS.map(([e,el])=>`<label><input type="checkbox" data-era="${e}" checked> ${el}</label>`).join('')}</div>${hidden}</div>`;
    $('#pklist').innerHTML=LANG==='en'?us:'<div class="pkcols">'+group('판례 · 해석례 · 심판',PACKS,'')+(IS_MOBILE?'':group('특허 공보 · IPC 섹션',PATS,'필요한 분야만 권장, 8GB 노트북은 1~2개'))+'</div>';   // 다른 나라 팩은 아예 표시하지 않음(국가는 첫 실행 때 정함)
    // 미국: (연방대법원 ∪ 체크한 주) × 체크한 시대 → 숨은 팩 체크박스 동기화. 초기값은 현재 선택 상태에서 역산
    const fresh=!ps.some(p=>p.installed);   // 첫 실행 기본값
    if(fresh&&LANG!=='en') document.querySelectorAll('#pklist input[data-k]').forEach(i=>{ i.checked=!i.dataset.k.startsWith('pat_'); });
    const uspk=[...document.querySelectorAll('#pklist .uspk')]; const selKeys=new Set(uspk.filter(i=>i.checked).map(i=>i.dataset.k));
    if(selKeys.size){ if([...selKeys].some(k=>k.startsWith('us_scotus_'))) $('#usScotus').checked=true; if([...selKeys].some(k=>/^us_fed(d_|_ca)/.test(k))) $('#usFedLower').checked=true; if([...selKeys].some(k=>k.startsWith('us_fed_other_'))) $('#usFedOther').checked=true; if([...selKeys].some(k=>k.startsWith('us_fed_cafc_'))) $('#usFedCafc').checked=true; document.querySelectorAll('#usgrid input').forEach(i=>{ if([...selKeys].some(k=>k.startsWith('us_'+i.dataset.st+'_'))) i.checked=true; }); const eras=new Set([...selKeys].map(k=>k.split('_').pop())); document.querySelectorAll('[data-era]').forEach(i=>i.checked=eras.has(i.dataset.era)); }
    if(fresh&&LANG==='en'){ if(!$('#usScotus').disabled) $('#usScotus').checked=true; if(!$('#usFedLower').disabled) $('#usFedLower').checked=true; }
    const syncPk=()=>{ const courts=[]; if($('#usScotus').checked) courts.push('us_scotus'); if($('#usFedOther').checked) courts.push('us_fed_other'); if($('#usFedCafc').checked) courts.push('us_fed_cafc'); document.querySelectorAll('#usgrid input:checked').forEach(i=>{ courts.push('us_'+i.dataset.st); if($('#usFedLower').checked) courts.push(...fedKeys(i.dataset.st)); }); const eras=[...document.querySelectorAll('[data-era]:checked')].map(i=>i.dataset.era);
      uspk.forEach(i=>{ const [_,c,e]=i.dataset.k.match(/^us_(.+)_([a-z]+)$/)||[]; i.checked=courts.includes('us_'+c)&&eras.includes(e); }); };
    bindDel();
    const usc=$('#usClear'); if(usc) usc.onclick=e=>{ e.preventDefault(); document.querySelectorAll('#usScotus, #usFedLower, #usFedCafc, #usFedOther, #usgrid input').forEach(i=>i.checked=false); syncPk(); sum(); };
    document.querySelectorAll('#usScotus, #usFedLower, #usFedCafc, #usFedOther, #usgrid input, [data-era]').forEach(i=>i.addEventListener('change',()=>{ syncPk(); sum(); }));
    if(fresh&&LANG==='en'){ syncPk(); }
    const sum=()=>{ const on=[...document.querySelectorAll('#pklist input[data-k]:checked')]; $('#pksum').textContent=L(`선택 ${on.length}개`,`${on.length} selected`)+` · ${mb(on.reduce((a,i)=>a+ +i.dataset.b,0))}`; };
    document.querySelectorAll('#pklist .gsel').forEach(a=>a.onclick=e=>{ e.preventDefault(); a.closest('.pkcard').querySelectorAll('input').forEach(i=>i.checked=a.dataset.on==='1'); sum(); });
    document.querySelectorAll('#pklist input').forEach(i=>i.onchange=sum); sum();
  }catch(e){ $('#pklist').innerHTML='<p class="band">'+esc(String(e))+'</p>'; } }
$('#pkclose').onclick=()=>$('#packs').classList.remove('on');
// ── 업데이트: 시작 시 1회 자동 + 패널에서 수동. 있으면 푸터에 '업데이트 N개 · 받기' ──
let UPD=[];
/* 데스크톱 앱 새 버전 안내(아이패드 제외): manifest app_version > 현재 버전이면 홈페이지로 연결 */
let APPV=null; const vnum=v=>(v||'').split('.').map(x=>parseInt(x)||0); const vnewer=(a,b)=>{ const x=vnum(a),y=vnum(b); for(let i=0;i<3;i++){ if((x[i]||0)!==(y[i]||0)) return (x[i]||0)>(y[i]||0); } return false; };
function drawAppUpd(){ const a=$('#appupd'); if(!a) return; if(!APPV||!vnewer(APPV.latest,APPV.current)){ a.hidden=true; return; } a.hidden=false; a.textContent=L(`앱 업데이트 있음 (v${APPV.latest}) · 홈페이지에서 받기`,`App update available (v${APPV.latest}) · Download from the website`);
  a.onclick=e=>{ e.preventDefault(); inv('open_url',{url:LANG==='en'?'https://nikh.hrmk.studio/en/':'https://nikh.hrmk.studio/'}).catch(()=>{}); }; }
async function checkAppUpdate(){ if(!IS_TAURI||IS_MOBILE) return; try{ APPV=await inv('app_update'); }catch(e){ APPV=null; } drawAppUpd(); }
setTimeout(checkAppUpdate,2000);
/* 준비 문구: 현재 국가 팩만 세고 현재 언어로(국가 전환 시 setLang 이 다시 그림) */
function readyText(s){ const us=LANG==='en'; const ks=(s.loaded||[]).filter(k=>us===k.startsWith('us_')); const per=s.per||{}; const n=ks.reduce((a,k)=>a+(+per[k]||0),0)||(ks.length===(s.loaded||[]).length?s.recs:0);
  return L('준비 완료 · '+n.toLocaleString()+'건 · 팩 '+ks.length+'개','Ready · '+n.toLocaleString()+' cases · '+ks.length+' packs'); }
async function checkUpdates(manual){ if(!IS_TAURI) return; try{ const ps=await inv('packs'); UPD=ps.filter(p=>p.update).map(p=>p.key); window.__UPDB=ps.filter(p=>p.update).reduce((a,p)=>a+(p.dl??p.bytes),0); }catch(e){ if(manual) $('#pkupd').textContent=L('확인 실패: ','Check failed: ')+e; return; }
  const n=UPD.length; const b=$('#upd'); b.style.display=n?'':'none'; const ub=window.__UPDB||0, us=ub>=1e9?(ub/1e9).toFixed(1)+' GB':Math.max(1,Math.round(ub/1e6))+' MB'; b.textContent=L(`업데이트 ${n}개 · ${us} 받기`,`${n} update${n>1?'s':''} · ${us} · Download`);
  if(manual) $('#pkupd').textContent=n?L(`업데이트 ${n}개: `,`${n} available: `)+UPD.map(k=>PLABEL[k]||k).join(', '):L('최신 상태입니다.','Everything is up to date.'); return n; }
async function applyUpdates(){ if(!UPD.length) return; const b=$('#upd'); const ps=await inv('packs'); const keep=ps.filter(p=>p.selected).map(p=>p.key); if(IS_MOBILE){ const bytes=ps.filter(p=>UPD.includes(p.key)).reduce((a,p)=>a+(p.dl??p.bytes),0); if(!(await cellWarn(bytes))) return; }
  for(const [i,k] of UPD.entries()){ const lab=(PLABEL[k]||k), pos=` (${i+1}/${UPD.length})`, mb=x=>x>=1e9?(x/1e9).toFixed(2)+' GB':(x/1e6).toFixed(1)+' MB'; b.textContent=lab+L(' 받는 중…',' downloading…')+pos;
    const tk=setInterval(async()=>{ try{ const s=await inv('stats'); if(s.label!==k) return; if(s.stage==='dl'&&s.total) b.textContent=lab+L(' 받는 중 ',' downloading ')+`${mb(s.done)} / ${mb(s.total)} · ${Math.min(100,Math.round(100*s.done/s.total))}%`+pos; else if(s.stage==='verify') b.textContent=lab+L(' 무결성 확인 중',' verifying integrity')+pos; }catch(e){} },400);
    try{ await inv('download_pack',{key:k}); }catch(e){ clearInterval(tk); b.textContent=lab+L(' 실패: ',' failed: ')+e; return; } clearInterval(tk); }
  UPD=[]; b.style.display='none'; await inv('select_packs',{keys:keep}); $('#ready').textContent=L('업데이트 적용 — 엔진을 다시 싣는 중','Updates applied — reloading the engine'); window.__ready=false; window.__reloading=true; setTimeout(()=>window.__poll&&window.__poll(),300); }
$('#upd').onclick=applyUpdates; $('#pkcheck').onclick=()=>{ $('#pkupd').textContent=L('확인 중…','Checking…'); checkUpdates(true).then(()=>{ if($('#packs').classList.contains('on')) openPacks(); }); };
function cellWarn(bytes){ return new Promise(res=>{ const m=$('#cellwarn'); const mb=b=>b>=1e9?(b/1e9).toFixed(1)+' GB':(b/1e6).toFixed(0)+' MB'; $('#cwTitle').textContent=L('셀룰러 요금 주의','Cellular data warning'); $('#cwText').textContent=L(`약 ${mb(bytes)}를 내려받습니다. 셀룰러(LTE/5G) 연결이면 데이터 요금이 크게 나올 수 있습니다. Wi-Fi에서 받는 것을 권합니다.`,`About ${mb(bytes)} will be downloaded. On a cellular (LTE/5G) connection this can use a lot of your data plan. Wi-Fi is recommended.`); $('#cwNo').textContent=L('취소','Cancel'); $('#cwYes').textContent=L('계속 받기','Download anyway'); m.hidden=false; $('#cwYes').onclick=()=>{ m.hidden=true; res(true); }; $('#cwNo').onclick=()=>{ m.hidden=true; res(false); }; }); }
$('#pkapply').onclick=async()=>{ const ab=$('#pkapply'); if(ab.disabled) return; ab.disabled=true; ab.style.opacity='.5'; ab.textContent=L('적용 중…','Applying…'); const keys=[...document.querySelectorAll('#pklist input[data-k]:checked')].map(i=>i.dataset.k); const st=$('#pkstatus');
  const by=Object.fromEntries((window.__PS||[]).map(p=>[p.key,p])); const need=keys.filter(k=>!(by[k]&&by[k].installed)||(by[k]&&by[k].update)); const ok=new Set(keys.filter(k=>by[k]&&by[k].installed)); const failed=[];
  const pg=$('#pkgauge'), pf=$('#pkgaugeFill'); const mbf=b=>(b/1e6).toFixed(0)+' MB'; let di=0;
  window.__firstApply=!(window.__PS||[]).some(p=>p.installed);
  if(IS_MOBILE){ let bytes=need.reduce((a,k)=>a+((by[k]&&(by[k].dl??by[k].bytes))||0),0); try{ const s0=await inv('stats'); if(s0&&s0.model===false) bytes+=586e6; }catch(e){} if(bytes>0&&!(await cellWarn(bytes))){ ab.disabled=false; ab.style.opacity=''; ab.textContent=L('선택한 팩 내려받기 · 적용','Download selected · Apply'); st.textContent=L('취소됨','Cancelled'); return; } }
  try{ const s0=await inv('stats'); if(s0&&s0.model===false){ pg.style.display=''; pf.style.width='0'; st.textContent=L('검색 모델 내려받는 중… (586 MB, 한 번만)','Downloading the search model… (586 MB, once)');
    const tick=setInterval(async()=>{ try{ const s=await inv('stats'); if(s.stage==='dl'&&s.total){ pf.style.width=Math.min(100,Math.round(100*s.done/s.total))+'%'; st.textContent=L('검색 모델 내려받는 중 ','Downloading the search model ')+`${mbf(s.done)} / ${mbf(s.total)}`; } }catch(e){} },400);
    try{ await inv('download_model'); }catch(e){ clearInterval(tick); pg.style.display='none'; st.textContent=L('모델 내려받기 실패: ','Model download failed: ')+e; ab.disabled=false; ab.style.opacity=''; ab.textContent=L('선택한 팩 내려받기 · 적용','Download selected · Apply'); return; } clearInterval(tick); } }catch(e){}
  for(const k of need){ di++; pg.style.display=''; pf.style.width='0'; st.textContent=(PLABEL[k]||k)+L(' 내려받는 중…',' downloading…')+` (${di}/${need.length})`;
    const tick=setInterval(async()=>{ try{ const s=await inv('stats'); if(s.stage==='dl'&&s.total){ pf.style.width=Math.min(100,Math.round(100*s.done/s.total))+'%'; st.textContent=(PLABEL[k]||k)+L(' 내려받는 중 ',' downloading ')+`${mbf(s.done)} / ${mbf(s.total)} (${di}/${need.length})`; } else if(s.stage==='verify'){ pf.style.width='100%'; st.textContent=(PLABEL[k]||k)+L(' 무결성 확인 중',' verifying integrity')+` (${di}/${need.length})`; } }catch(e){} },400);
    try{ await inv('download_pack',{key:k}); ok.add(k); }catch(e){ failed.push(k); if(!(by[k]&&by[k].installed)) ok.delete(k); } clearInterval(tick); }
  pg.style.display='none';   // 서버가 없으면 설치본은 그대로 쓰고 미설치만 건너뜀
  try{ await inv('select_packs',{keys:[...ok]}); }catch(e){ ab.disabled=false; ab.style.opacity=''; ab.textContent=L('선택한 팩 내려받기 · 적용','Download selected · Apply'); st.textContent=L('적용 실패: ','Apply failed: ')+e; return; } window.__ready=false; window.__reloading=true; setTimeout(()=>window.__poll&&window.__poll(),300);
  st.textContent=(failed.length?L(`받지 못한 팩 ${failed.length}개(서버 연결 안 됨: ${failed.slice(0,3).map(k=>PLABEL[k]||k).join(', ')}${failed.length>3?' …':''}) · `,`${failed.length} pack${failed.length>1?'s':''} not downloaded (no server: ${failed.slice(0,3).map(k=>PLABEL[k]||k).join(', ')}${failed.length>3?' …':''}) · `):'')+L('적용됨 — 엔진을 다시 싣는 중입니다. 준비 완료가 뜨면 검색하세요.','Applied — reloading the engine. Search once the footer says Ready.'); $('#pkintro').hidden=true; };
// ── 전체화면 리더: 심급 수만큼 분할 ──
