// 미국 범위(주·연방·시대)·모드·문구 테이블
function drawUS(){ $('#usel').hidden=false; $('#scope').innerHTML='';
  const has=k=>!LOADED||LOADED.some(x=>x.startsWith(k+'_')); const name=k=>k==='us_scotus'?'U.S. Supreme Court':((STATES.find(([c])=>'us_'+c===k)||[])[1]||k);
  if(US_STATE&&!has(US_STATE)){ US_STATE=null; US_ERAS.clear(); }   // 메모리에서 내린 주는 선택 해제
  if(US_PATENT&&!has('us_fed_cafc')) US_PATENT=false;
  const fedOk=has('us_scotus'); $('#usfed').innerHTML=`<span class="st ${US_SCOTUS&&fedOk?'on':''} ${fedOk?'':'dim'}" id="usfedchip" title="${fedOk?'Supreme Court + your state’s circuit court of appeals + federal district courts — click to exclude':'pack not installed'}">${US_SCOTUS&&fedOk?'✓ ':''}Federal courts</span><span class="st ${US_PATENT?'on':''} ${has('us_fed_cafc')?'':'dim'}" id="uspatent" title="Federal Circuit · CCPA · E.D./W.D. Tex. · D. Del. · N.D. Cal. — patent litigation venues (state selection not needed)">${US_PATENT?'✓ ':''}Patent courts</span>${US_SCOTUS&&fedOk&&!US_PATENT?`<span class="st ${US_ALLCIRC?'on':''}" id="usallcirc" title="Add every circuit court of appeals (circuit splits, persuasive authority)">${US_ALLCIRC?'✓ ':''}All circuits</span>`:''}`;
  $('#ustates').innerHTML=STATES.map(([c,n])=>`<span class="st ${US_STATE==='us_'+c?'on':''} ${has('us_'+c)?'':'dim'}" data-k="us_${c}" title="${escapeHtml(n)}${has('us_'+c)?'':' · pack not installed'}">${c.toUpperCase()}</span>`).join('');
  const fed=US_SCOTUS&&fedOk; $('#ussel').textContent=US_PATENT?'Patent courts (Fed. Cir. · CCPA · E.D./W.D. Tex. · D. Del. · N.D. Cal. · SCOTUS)'+(US_ERAS.size?' · '+[...US_ERAS].map(e=>(ERAS.find(([k])=>k===e)||[])[1]||e).join(' · '):' · all eras'):(US_STATE||fed)?[US_STATE?name(US_STATE):null,fed?(US_STATE&&CIRCUIT_OF_STATE[US_STATE.slice(3)]?`Federal (SCOTUS · Fed. Cir. · ${US_ALLCIRC?'all circuits · ':''}${CIRCUIT_OF_STATE[US_STATE.slice(3)]==='dc'?'D.C.':CIRCUIT_OF_STATE[US_STATE.slice(3)]+(({1:'st',2:'d',3:'d'})[CIRCUIT_OF_STATE[US_STATE.slice(3)]]||'th')} Cir. · D. ${US_STATE.slice(3).toUpperCase()})`:'U.S. Supreme Court'):null].filter(Boolean).join(' + ')+(US_ERAS.size?' · '+[...US_ERAS].map(e=>(ERAS.find(([k])=>k===e)||[])[1]||e).join(' · '):' · all eras'):'Pick your state. Grey = pack not installed (see Data packs below).';
  $('#useras').innerHTML=(US_STATE||fed||US_PATENT)?ERAS.map(([e,el])=>`<span class="er ${US_ERAS.size===0||US_ERAS.has(e)?'on':''}" data-e="${e}">${escapeHtml(el)}</span>`).join(''):'';
  const pc=$('#uspatent'); if(pc) pc.onclick=()=>{ if(pc.classList.contains('dim')) return; US_PATENT=!US_PATENT; syncUS(); drawUS(); if(IS_TAURI) invoke('prewarm',{mode:'us'}).catch(()=>{}); if(queryInput.value.trim()) runSearch(); else queryInput.focus(); };
  const ac=$('#usallcirc'); if(ac) ac.onclick=()=>{ US_ALLCIRC=!US_ALLCIRC; syncUS(); drawUS(); if(IS_TAURI) invoke('prewarm',{mode:'us'}).catch(()=>{}); if(queryInput.value.trim()) runSearch(); };
  $('#usfedchip').onclick=()=>{ if(!fedOk) return; US_SCOTUS=!US_SCOTUS; syncUS(); drawUS(); if(IS_TAURI) invoke('prewarm',{mode:'us'}).catch(()=>{}); if(queryInput.value.trim()) runSearch(); };
  document.querySelectorAll('#ustates .st').forEach(c=>c.onclick=()=>{ if(c.classList.contains('dim')) return; US_STATE=US_STATE===c.dataset.k?null:c.dataset.k; US_ERAS.clear(); syncUS(); drawUS(); if(IS_TAURI) invoke('prewarm',{mode:'us'}).catch(()=>{}); if(US_STATE&&queryInput.value.trim()) runSearch(); else queryInput.focus(); });
  document.querySelectorAll('#useras .er').forEach(c=>c.onclick=()=>{ const e=c.dataset.e; if(US_ERAS.has(e)) US_ERAS.delete(e); else US_ERAS.add(e); if(US_ERAS.size===ERAS.length) US_ERAS.clear(); syncUS(); drawUS(); if(queryInput.value.trim()) runSearch(); }); }
function syncUS(){ SCOPE.us=new Set(); const fedOk=!LOADED||LOADED.some(x=>x.startsWith('us_scotus_')); const ks=US_PATENT?[...PATENT_COURTS]:[US_STATE]; if(!US_PATENT&&US_SCOTUS&&fedOk){ ks.push('us_scotus', 'us_fed_cafc', ...federalPackKeys(US_STATE)); if(US_ALLCIRC) for(const c of [1,2,3,4,5,6,7,8,9,10,11,'dc']) ks.push('us_fed_ca'+c); } for(const k of ks) if(k) for(const [e] of ERAS) if(US_ERAS.size===0||US_ERAS.has(e)) SCOPE.us.add(k+'_'+e); }
function drawScope(){ if(MODE==='us'){ drawUS(); return; } $('#usel').hidden=true; const list=(MODE==='patent'?PATENT_PACKS:PACKS).filter(([k])=>!LOADED||LOADED.includes(k)); const sel=SCOPE[MODE]||(SCOPE[MODE]=new Set());
  $('#scope').innerHTML=`<span class="c all ${sel.size?'':'on'}" data-k="">전체</span>`+list.map(([k,l])=>`<span class="c ${sel.has(k)?'on':''}" data-k="${k}" title="${escapeHtml(l)}">${escapeHtml(CHIP_LABEL[k]||l)}</span>`).join('');
  document.querySelectorAll('#scope .c').forEach(c=>c.onclick=()=>{ const k=c.dataset.k; if(!k) sel.clear(); else if(sel.has(k)) sel.delete(k); else sel.add(k); drawScope(); if(queryInput.value.trim()) runSearch(); }); }
function modeParam(){ const sel=SCOPE[MODE]||new Set(); return sel.size?('packs:'+[...sel].join(',')):MODE; }
let MODE='case'; const PLACEHOLDER={case:'자연스럽게 의뢰인의 현 상황을 입력해 주세요',patent:'이런 발명이 이미 있는지 — 기술 내용을 자연스럽게 적어 주세요',us:'Describe your client\'s situation in plain English'};
const US_PRESETS=[['us_scotus','U.S. Supreme Court'],['us_de','Delaware'],['us_ca','California'],['us_tx','Texas'],['us_ny','New York']];
const STATES=[['al','Alabama'],['ak','Alaska'],['az','Arizona'],['ar','Arkansas'],['ca','California'],['co','Colorado'],['ct','Connecticut'],['de','Delaware'],['dc','D.C.'],['fl','Florida'],['ga','Georgia'],['hi','Hawaii'],['id','Idaho'],['il','Illinois'],['in','Indiana'],['ia','Iowa'],['ks','Kansas'],['ky','Kentucky'],['la','Louisiana'],['me','Maine'],['md','Maryland'],['ma','Massachusetts'],['mi','Michigan'],['mn','Minnesota'],['ms','Mississippi'],['mo','Missouri'],['mt','Montana'],['ne','Nebraska'],['nv','Nevada'],['nh','New Hampshire'],['nj','New Jersey'],['nm','New Mexico'],['ny','New York'],['nc','North Carolina'],['nd','North Dakota'],['oh','Ohio'],['ok','Oklahoma'],['or','Oregon'],['pa','Pennsylvania'],['ri','Rhode Island'],['sc','South Carolina'],['sd','South Dakota'],['tn','Tennessee'],['tx','Texas'],['ut','Utah'],['vt','Vermont'],['va','Virginia'],['wa','Washington'],['wv','West Virginia'],['wi','Wisconsin'],['wy','Wyoming']];
const ERAS=[['antique','Antique (–1937)'],['classics','Classics (1938–89)'],['modern','Modern (1990–2019)'],['contemporary','Contemporary (2020–)']];
for(const [k,l] of US_PRESETS) for(const [e,el] of ERAS) PACK_LABEL[k+'_'+e]=l+' · '+el;
for(const [c,n] of STATES) for(const [e,el] of ERAS) PACK_LABEL['us_'+c+'_'+e]=n+' · '+el;   // ERAS 정의 뒤
for(const [c,n] of STATES) for(const [e,el] of ERAS) PACK_LABEL['us_fedd_'+c+'_'+e]='Federal district & bankruptcy · '+n+' · '+el;
for(const c of [1,2,3,4,5,6,7,8,9,10,11,'dc','fc']) for(const [e,el] of ERAS) PACK_LABEL['us_fed_ca'+c+'_'+e]='U.S. Court of Appeals · '+(c==='dc'?'D.C.':c==='fc'?'Fed.':c+(({1:'st',2:'d',3:'d'})[c]||'th'))+' Cir. · '+el;
for(const [e,el] of ERAS) PACK_LABEL['us_fed_other_'+e]='Other federal courts · '+el;
const tr=(ko,en)=>LANG==='en'?en:ko;   // 국가별 문구(전수 적용)
let LANG='ko'; const TEXT={ko:{modes:['판례 · 해석례 · 심판','특허'],go:'검색',foot:'결과는 판례 원문·메타·규칙 태그만 표시합니다. 요약·생성 없음 · 입력은 저장되지 않습니다',k:'결과',hyb:'조문·용어 정확일치 우선'},
  en:{modes:['U.S. Cases',''],go:'Search',foot:'Results show original opinions, metadata and rule-based tags only. No summaries, nothing generated, nothing stored.',k:'Results',hyb:'Prefer exact statute/term match'}};
